/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as StoryIdRouteImport } from './routes/story.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/story/$id': typeof StoryIdRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/story/$id': typeof StoryIdRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/story/$id': typeof StoryIdRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/search' | '/story/$id' | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/search' | '/story/$id' | '/user/$id'
  id: '__root__' | '/' | '/live' | '/search' | '/story/$id' | '/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  SearchRoute: typeof SearchRoute
  StoryIdRoute: typeof StoryIdRoute
  UserIdRoute: typeof UserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  SearchRoute: SearchRoute,
  StoryIdRoute: StoryIdRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
